# Generated by Django 2.0.5 on 2018-05-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='image',
            field=models.URLField(),
        ),
    ]
