# Generated by Django 2.0.5 on 2018-05-31 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20180531_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='about_title',
            new_name='article_title',
        ),
    ]
